name: Swift CI & Docs

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  build-and-docs:
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Select Xcode 16.2
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      - name: Print Swift version
        run: swift --version

      - name: Build Package
        run: swift build -v

      - name: Generate DocC
        run: |
         mkdir -p docs
         xcodebuild docbuild \
          -scheme RKPurchaseKit \
          -destination 'platform=macOS' \
          -derivedDataPath docs-build

         $(xcrun --find docc) process-archive \
         transform-for-static-hosting docs-build/Build/Products/Debug/RKPurchaseKit.doccarchive \
           --output-path docs \
           --hosting-base-path PurchaseKit

      - name: Add index.html redirect
        run: |
          echo '<!DOCTYPE html><html><head><meta http-equiv="refresh" content="0; url=documentation/rkpurchasekit/"></head><body></body></html>' > docs/index.html
      
      - name: Commit and Push Docs to Main
        if: github.ref == 'refs/heads/main'
        run: |
         git config user.name github-actions
         git config user.email github-actions@github.com
         git add docs
         git commit -m "📚 Update documentation" --allow-empty
         git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
