name: Swift CI

on:
  pull_request:
    branches: [ main, development ]
  push:
    branches: [ main, development ]

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build package
        run: swift build -v
